// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for FacetField.
const (
	Actor     FacetField = "actor"
	Kind      FacetField = "kind"
	Namespace FacetField = "namespace"
)

// Defines values for Operation.
const (
	CONNECT Operation = "CONNECT"
	CREATE  Operation = "CREATE"
	DELETE  Operation = "DELETE"
	UPDATE  Operation = "UPDATE"
)

// AuditEvent One audit event, projected to the lifted (searchable) columns.
type AuditEvent struct {
	ApiGroup   string                    `json:"apiGroup"`
	ApiVersion string                    `json:"apiVersion"`
	DryRun     bool                      `json:"dryRun"`
	EventUid   string                    `json:"eventUid"`
	Kind       string                    `json:"kind"`
	Name       string                    `json:"name"`
	Namespace  string                    `json:"namespace"`
	ObjectUid  nullable.Nullable[string] `json:"objectUid,omitempty"`

	// Operation The admission operation recorded on an event.
	Operation   Operation                 `json:"operation"`
	ReceivedAt  time.Time                 `json:"receivedAt"`
	Resource    string                    `json:"resource"`
	SubResource nullable.Nullable[string] `json:"subResource,omitempty"`
	Username    string                    `json:"username"`
}

// AuditEventsResponse defines model for AuditEventsResponse.
type AuditEventsResponse struct {
	Data       []AuditEvent `json:"data"`
	Pagination Pagination   `json:"pagination"`
}

// AuditFacetsResponse Distinct, sorted, non-null values per requested facet field. Only the requested fields are present; unrequested fields are omitted entirely.
type AuditFacetsResponse struct {
	// Actor The distinct values for one facet field, capped at 50. When more than 50 distinct values exist, values is empty and truncated is true — the client should fall back to free-text input rather than trust a partial dropdown.
	Actor *Facet `json:"actor,omitempty"`

	// Kind The distinct values for one facet field, capped at 50. When more than 50 distinct values exist, values is empty and truncated is true — the client should fall back to free-text input rather than trust a partial dropdown.
	Kind *Facet `json:"kind,omitempty"`

	// Namespace The distinct values for one facet field, capped at 50. When more than 50 distinct values exist, values is empty and truncated is true — the client should fall back to free-text input rather than trust a partial dropdown.
	Namespace *Facet `json:"namespace,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code A short error code representing the type of error.
	Code string `json:"code"`

	// Message A human-readable message providing more details about the error.
	Message string `json:"message"`
}

// Facet The distinct values for one facet field, capped at 50. When more than 50 distinct values exist, values is empty and truncated is true — the client should fall back to free-text input rather than trust a partial dropdown.
type Facet struct {
	// Truncated True when more than the cap (50) distinct values exist; values is then empty and the client should use free-text input.
	Truncated bool     `json:"truncated"`
	Values    []string `json:"values"`
}

// FacetField A whitelisted, filterable field with a bounded set of distinct values.
type FacetField string

// Initiator The CREATE actor of an object, or an empty result when never audited.
type Initiator struct {
	// Actor The username that created the object.
	Actor *string `json:"actor,omitempty"`

	// Found Whether a CREATE audit event exists for the object.
	Found bool `json:"found"`

	// Operation The admission operation recorded on an event.
	Operation *Operation `json:"operation,omitempty"`

	// Timestamp When the creating event was received.
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// Operation The admission operation recorded on an event.
type Operation string

// Pagination defines model for Pagination.
type Pagination struct {
	Page    int `json:"page"`
	PerPage int `json:"perPage"`
	Total   int `json:"total"`
}

// ActorParam defines model for actorParam.
type ActorParam = string

// FacetFieldsParam defines model for facetFieldsParam.
type FacetFieldsParam = []FacetField

// FromParam defines model for fromParam.
type FromParam = time.Time

// GroupParam defines model for groupParam.
type GroupParam = string

// KindParam defines model for kindParam.
type KindParam = string

// NameParam defines model for nameParam.
type NameParam = string

// NamespaceParam defines model for namespaceParam.
type NamespaceParam = string

// ObjectUidParam defines model for objectUidParam.
type ObjectUidParam = string

// OperationParam The admission operation recorded on an event.
type OperationParam = Operation

// PageParam defines model for pageParam.
type PageParam = int

// PerPageParam defines model for perPageParam.
type PerPageParam = int

// ResourceParam defines model for resourceParam.
type ResourceParam = string

// ToParam defines model for toParam.
type ToParam = time.Time

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	// Actor The acting username (request.userInfo.username).
	Actor *ActorParam `form:"actor,omitempty" json:"actor,omitempty"`

	// Operation The admission operation.
	Operation *OperationParam `form:"operation,omitempty" json:"operation,omitempty"`

	// Group The API group of the resource (request.resource.group).
	Group *GroupParam `form:"group,omitempty" json:"group,omitempty"`

	// Resource The resource (plural, e.g. pipelineruns).
	Resource *ResourceParam `form:"resource,omitempty" json:"resource,omitempty"`

	// Kind The Kubernetes object kind (e.g. PipelineRun).
	Kind *KindParam `form:"kind,omitempty" json:"kind,omitempty"`

	// Namespace The object's namespace.
	Namespace *NamespaceParam `form:"namespace,omitempty" json:"namespace,omitempty"`

	// Name The object's name.
	Name *NameParam `form:"name,omitempty" json:"name,omitempty"`

	// ObjectUid The object's metadata.uid (stable correlation key across its lifecycle).
	ObjectUid *ObjectUidParam `form:"objectUid,omitempty" json:"objectUid,omitempty"`

	// From Inclusive lower bound on received_at (RFC 3339).
	From *FromParam `form:"from,omitempty" json:"from,omitempty"`

	// To Exclusive upper bound on received_at (RFC 3339).
	To *ToParam `form:"to,omitempty" json:"to,omitempty"`

	// Page 1-based page number (default 1).
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Page size (default 20, max 100).
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// ListAuditFacetsParams defines parameters for ListAuditFacets.
type ListAuditFacetsParams struct {
	// Fields The facet fields to return, comma-separated. Defaults to all facet fields (namespace, kind, actor) when omitted.
	Fields *FacetFieldsParam `form:"fields,omitempty" json:"fields,omitempty"`
}

// GetInitiatorParams defines parameters for GetInitiator.
type GetInitiatorParams struct {
	// ObjectUid The object's metadata.uid (stable correlation key across its lifecycle).
	ObjectUid *ObjectUidParam `form:"objectUid,omitempty" json:"objectUid,omitempty"`

	// Kind The Kubernetes object kind (e.g. PipelineRun).
	Kind *KindParam `form:"kind,omitempty" json:"kind,omitempty"`

	// Namespace The object's namespace.
	Namespace *NamespaceParam `form:"namespace,omitempty" json:"namespace,omitempty"`

	// Name The object's name.
	Name *NameParam `form:"name,omitempty" json:"name,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Query audit events
	// (GET /api/v1/audit/events)
	ListAuditEvents(w http.ResponseWriter, r *http.Request, params ListAuditEventsParams)
	// List distinct values for the given facet fields
	// (GET /api/v1/audit/facets)
	ListAuditFacets(w http.ResponseWriter, r *http.Request, params ListAuditFacetsParams)
	// Resolve who created a Kubernetes object
	// (GET /api/v1/audit/initiator)
	GetInitiator(w http.ResponseWriter, r *http.Request, params GetInitiatorParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Query audit events
// (GET /api/v1/audit/events)
func (_ Unimplemented) ListAuditEvents(w http.ResponseWriter, r *http.Request, params ListAuditEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List distinct values for the given facet fields
// (GET /api/v1/audit/facets)
func (_ Unimplemented) ListAuditFacets(w http.ResponseWriter, r *http.Request, params ListAuditFacetsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resolve who created a Kubernetes object
// (GET /api/v1/audit/initiator)
func (_ Unimplemented) GetInitiator(w http.ResponseWriter, r *http.Request, params GetInitiatorParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) ListAuditEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditEventsParams

	// ------------- Optional query parameter "actor" -------------

	err = runtime.BindQueryParameter("form", true, false, "actor", r.URL.Query(), &params.Actor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "actor", Err: err})
		return
	}

	// ------------- Optional query parameter "operation" -------------

	err = runtime.BindQueryParameter("form", true, false, "operation", r.URL.Query(), &params.Operation)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation", Err: err})
		return
	}

	// ------------- Optional query parameter "group" -------------

	err = runtime.BindQueryParameter("form", true, false, "group", r.URL.Query(), &params.Group)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group", Err: err})
		return
	}

	// ------------- Optional query parameter "resource" -------------

	err = runtime.BindQueryParameter("form", true, false, "resource", r.URL.Query(), &params.Resource)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resource", Err: err})
		return
	}

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameter("form", true, false, "kind", r.URL.Query(), &params.Kind)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "objectUid" -------------

	err = runtime.BindQueryParameter("form", true, false, "objectUid", r.URL.Query(), &params.ObjectUid)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "objectUid", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameter("form", true, false, "perPage", r.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuditEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAuditFacets operation middleware
func (siw *ServerInterfaceWrapper) ListAuditFacets(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditFacetsParams

	// ------------- Optional query parameter "fields" -------------

	err = runtime.BindQueryParameter("form", false, false, "fields", r.URL.Query(), &params.Fields)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fields", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuditFacets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInitiator operation middleware
func (siw *ServerInterfaceWrapper) GetInitiator(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInitiatorParams

	// ------------- Optional query parameter "objectUid" -------------

	err = runtime.BindQueryParameter("form", true, false, "objectUid", r.URL.Query(), &params.ObjectUid)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "objectUid", Err: err})
		return
	}

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameter("form", true, false, "kind", r.URL.Query(), &params.Kind)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInitiator(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/audit/events", wrapper.ListAuditEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/audit/facets", wrapper.ListAuditFacets)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/audit/initiator", wrapper.GetInitiator)
	})

	return r
}

type ListAuditEventsRequestObject struct {
	Params ListAuditEventsParams
}

type ListAuditEventsResponseObject interface {
	VisitListAuditEventsResponse(w http.ResponseWriter) error
}

type ListAuditEvents200JSONResponse AuditEventsResponse

func (response ListAuditEvents200JSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAuditEvents400JSONResponse Error

func (response ListAuditEvents400JSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListAuditEvents500JSONResponse Error

func (response ListAuditEvents500JSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListAuditFacetsRequestObject struct {
	Params ListAuditFacetsParams
}

type ListAuditFacetsResponseObject interface {
	VisitListAuditFacetsResponse(w http.ResponseWriter) error
}

type ListAuditFacets200JSONResponse AuditFacetsResponse

func (response ListAuditFacets200JSONResponse) VisitListAuditFacetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAuditFacets400JSONResponse Error

func (response ListAuditFacets400JSONResponse) VisitListAuditFacetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListAuditFacets500JSONResponse Error

func (response ListAuditFacets500JSONResponse) VisitListAuditFacetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetInitiatorRequestObject struct {
	Params GetInitiatorParams
}

type GetInitiatorResponseObject interface {
	VisitGetInitiatorResponse(w http.ResponseWriter) error
}

type GetInitiator200JSONResponse Initiator

func (response GetInitiator200JSONResponse) VisitGetInitiatorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetInitiator400JSONResponse Error

func (response GetInitiator400JSONResponse) VisitGetInitiatorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetInitiator500JSONResponse Error

func (response GetInitiator500JSONResponse) VisitGetInitiatorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Query audit events
	// (GET /api/v1/audit/events)
	ListAuditEvents(ctx context.Context, request ListAuditEventsRequestObject) (ListAuditEventsResponseObject, error)
	// List distinct values for the given facet fields
	// (GET /api/v1/audit/facets)
	ListAuditFacets(ctx context.Context, request ListAuditFacetsRequestObject) (ListAuditFacetsResponseObject, error)
	// Resolve who created a Kubernetes object
	// (GET /api/v1/audit/initiator)
	GetInitiator(ctx context.Context, request GetInitiatorRequestObject) (GetInitiatorResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAuditEvents operation middleware
func (sh *strictHandler) ListAuditEvents(w http.ResponseWriter, r *http.Request, params ListAuditEventsParams) {
	var request ListAuditEventsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAuditEvents(ctx, request.(ListAuditEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAuditEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAuditEventsResponseObject); ok {
		if err := validResponse.VisitListAuditEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAuditFacets operation middleware
func (sh *strictHandler) ListAuditFacets(w http.ResponseWriter, r *http.Request, params ListAuditFacetsParams) {
	var request ListAuditFacetsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAuditFacets(ctx, request.(ListAuditFacetsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAuditFacets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAuditFacetsResponseObject); ok {
		if err := validResponse.VisitListAuditFacetsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInitiator operation middleware
func (sh *strictHandler) GetInitiator(w http.ResponseWriter, r *http.Request, params GetInitiatorParams) {
	var request GetInitiatorRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInitiator(ctx, request.(GetInitiatorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInitiator")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInitiatorResponseObject); ok {
		if err := validResponse.VisitGetInitiatorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
