{{- if .Values.eso.enabled }}
apiVersion: {{ .Values.eso.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "krci-audit.dbAccessSecretName" . }}
  labels:
    {{- include "krci-audit.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ include "krci-audit.fullname" . }}
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.eso.secretPath }}
        metadataPolicy: None
{{- end }}
