{{- if .Values.eso.enabled }}
apiVersion: {{ .Values.eso.apiVersion }}
kind: SecretStore
metadata:
  name: {{ include "krci-audit.fullname" . }}
  labels:
    {{- include "krci-audit.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.eso.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "krci-audit.fullname" . }}-eso
{{- end }}
