{{- if .Values.eso.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "krci-audit.fullname" . }}-eso
  labels:
    {{- include "krci-audit.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.eso.aws.roleArn | quote }}
{{- end }}
