{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "krci-audit.serviceAccountName" . }}
  labels:
    {{- include "krci-audit.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
